// Original bilingual content for MAQLAB.
// bluff:  obscure-but-true facts; players invent fake answers.
// number: numeric answers; closest guess wins.
// blitz:  true/false statements for speed rounds.

const bluff = [
  { q: { ar: 'قبل أن يصبح لعبة أطفال، ما الاستخدام الأصلي لمعجون اللعب "Play-Doh"؟', en: 'Before it became a toy, what was Play-Doh originally sold as?' }, a: { ar: 'منظف ورق الجدران', en: 'Wallpaper cleaner' }, alt: ['منظف جدران', 'منظف للجدران', 'wall cleaner', 'wallpaper cleaning'] },
  { q: { ar: 'ما لون لسان الزرافة؟', en: "What colour is a giraffe's tongue?" }, a: { ar: 'أزرق داكن', en: 'Dark blue' }, alt: ['ازرق', 'بنفسجي', 'اسود', 'أزرق مسود', 'blue', 'purple', 'black', 'blue-black'] },
  { q: { ar: 'ما الكوكب الذي يومه أطول من سنته؟', en: 'Which planet has a day that is longer than its year?' }, a: { ar: 'الزهرة', en: 'Venus' }, alt: ['كوكب الزهرة'] },
  { q: { ar: 'ماذا استخدم شعب الأزتك كعملة إلى جانب أشياء أخرى؟', en: 'What did the Aztecs use as money, among other things?' }, a: { ar: 'حبوب الكاكاو', en: 'Cocoa beans' }, alt: ['الكاكاو', 'كاكاو', 'cacao beans', 'cocoa', 'cacao'] },
  { q: { ar: 'ما الحيوان الوطني الرسمي لاسكتلندا؟', en: 'What is the official national animal of Scotland?' }, a: { ar: 'اليونيكورن', en: 'The unicorn' }, alt: ['يونيكورن', 'وحيد القرن الأسطوري', 'الحصان وحيد القرن', 'unicorn'] },
  { q: { ar: 'ما الدولة الوحيدة في العالم التي علمها ليس مستطيلاً ولا مربعاً؟', en: 'Which is the only country whose flag is not a rectangle or square?' }, a: { ar: 'نيبال', en: 'Nepal' } },
  { q: { ar: 'ما الطعام الوحيد الذي لا يفسد تقريباً أبداً إذا حُفظ جيداً؟', en: 'Which food basically never spoils if stored properly?' }, a: { ar: 'العسل', en: 'Honey' } },
  { q: { ar: 'ما الرياضة التي مارسها رائد فضاء على سطح القمر عام 1971؟', en: 'Which sport did an astronaut play on the Moon in 1971?' }, a: { ar: 'الغولف', en: 'Golf' }, alt: ['قولف', 'جولف'] },
  { q: { ar: 'ما اسم النقطة الصغيرة فوق حرفي i و j في الإنجليزية؟', en: 'What is the dot above a lowercase i or j called?' }, a: { ar: 'تيتل', en: 'Tittle' }, alt: ['tittle', 'التيتل'] },
  { q: { ar: 'فضلات أي حيوان تكون على شكل مكعبات؟', en: "Which animal's poop is cube-shaped?" }, a: { ar: 'الومبت', en: 'Wombat' }, alt: ['ومبت', 'الومبات', 'ومبات', 'the wombat'] },
  { q: { ar: 'ما الطعام الذي يُقال إنه الأكثر سرقة من المتاجر في العالم؟', en: 'Which food is said to be the most stolen from shops worldwide?' }, a: { ar: 'الجبن', en: 'Cheese' }, alt: ['الجبنة', 'جبنة', 'جبن'] },
  { q: { ar: 'كيف كان يُباع مشروب كوكاكولا في بدايته؟', en: 'How was Coca-Cola originally sold?' }, a: { ar: 'كدواء', en: 'As a medicine' }, alt: ['دواء', 'علاج', 'مقوي', 'medicine', 'tonic', 'as a tonic'] },
  { q: { ar: 'ما الحيوان البري الكبير الذي لا يستطيع القفز؟', en: 'Which big land animal cannot jump?' }, a: { ar: 'الفيل', en: 'The elephant' }, alt: ['فيل', 'elephant'] },
  { q: { ar: 'ما الفاكهة التي تطفو على الماء لأن ربعها تقريباً هواء؟', en: 'Which fruit floats because about a quarter of it is air?' }, a: { ar: 'التفاح', en: 'Apple' }, alt: ['تفاحة', 'تفاح', 'the apple', 'apples'] },
  { q: { ar: 'ما أول لعبة أطفال أُعلن عنها على التلفزيون؟', en: 'What was the first toy ever advertised on TV?' }, a: { ar: 'السيد رأس البطاطس', en: 'Mr. Potato Head' }, alt: ['رأس البطاطس', 'مستر بوتيتو هيد', 'potato head', 'mr potato head'] },
  { q: { ar: 'ما الدولة التي تحتوي على أكبر عدد من البحيرات في العالم؟', en: 'Which country has the most lakes in the world?' }, a: { ar: 'كندا', en: 'Canada' } },
  { q: { ar: 'كليوباترا عاشت في زمن أقرب إلى هبوط الإنسان على القمر منه إلى بناء ماذا؟', en: 'Cleopatra lived closer in time to the Moon landing than to the building of what?' }, a: { ar: 'الهرم الأكبر', en: 'The Great Pyramid' }, alt: ['الاهرامات', 'أهرامات الجيزة', 'الهرم', 'pyramids', 'great pyramid of giza', 'the pyramids'] },
  { q: { ar: 'ماذا يُسمّى صغير الكنغر؟', en: 'What is a baby kangaroo called?' }, a: { ar: 'جوي', en: 'Joey' }, alt: ['joey'] },
  { q: { ar: 'أي معدن كان يوماً أغلى من الذهب لدرجة أن نابليون خصّصه لأدوات مائدة كبار ضيوفه؟', en: 'Which metal was once so precious that Napoleon kept cutlery of it for his top guests?' }, a: { ar: 'الألمنيوم', en: 'Aluminium' }, alt: ['المنيوم', 'الألومنيوم', 'aluminum'] },
  { q: { ar: 'أسماك القرش أقدم وجوداً على الأرض من ماذا؟', en: 'Sharks have existed on Earth longer than what?' }, a: { ar: 'الأشجار', en: 'Trees' }, alt: ['الشجر', 'شجر'] },
  { q: { ar: 'ما اللون الأصلي للجزر قبل أن يصبح برتقالياً؟', en: 'What colour were carrots before they became orange?' }, a: { ar: 'بنفسجي', en: 'Purple' }, alt: ['البنفسجي', 'ارجواني', 'violet'] },
  { q: { ar: 'في سويسرا، يُمنع قانوناً امتلاك واحد فقط من أي حيوان أليف؟', en: 'In Switzerland it is illegal to own just one of which pet?' }, a: { ar: 'خنزير غينيا', en: 'Guinea pig' }, alt: ['خنازير غينيا', 'guinea pigs'] },
  { q: { ar: 'مجموعة الغربان تُسمّى في الإنجليزية بكلمة تعني...؟', en: 'In English, a group of crows is called a...?' }, a: { ar: 'جريمة', en: 'Murder' }, alt: ['الجريمة'] },
  { q: { ar: 'نحل العسل قادر على التعرف على ماذا لدى البشر؟', en: 'Honeybees can learn to recognise what on humans?' }, a: { ar: 'الوجوه', en: 'Faces' }, alt: ['الوجه', 'وجوه', 'face'] },
  { q: { ar: 'أصغر عظمة في جسم الإنسان موجودة في أي عضو؟', en: 'The smallest bone in the human body is found in which body part?' }, a: { ar: 'الأذن', en: 'The ear' }, alt: ['الاذن', 'اذن', 'ear'] },
  { q: { ar: 'أي حيوان يملك بصمات أصابع تشبه بصمات الإنسان جداً؟', en: 'Which animal has fingerprints almost identical to human ones?' }, a: { ar: 'الكوالا', en: 'Koala' }, alt: ['كوالا', 'the koala'] },
  { q: { ar: 'ما أول غرض بيع على موقع eBay؟', en: 'What was the first item ever sold on eBay?' }, a: { ar: 'مؤشر ليزر مكسور', en: 'A broken laser pointer' }, alt: ['مؤشر ليزر', 'ليزر مكسور', 'laser pointer', 'broken laser pointer'] },
  { q: { ar: 'شعب أي دولة يشرب أكبر كمية من القهوة للفرد؟', en: 'Which country drinks the most coffee per person?' }, a: { ar: 'فنلندا', en: 'Finland' } },
  { q: { ar: 'أيهما اختُرع أولاً: الولاعة أم أعواد الثقاب؟', en: 'Which was invented first: the lighter or the match?' }, a: { ar: 'الولاعة', en: 'The lighter' }, alt: ['ولاعة', 'lighter'] },
  { q: { ar: 'في أي دولة اختُرعت بيتزا "هاواي" بالأناناس؟', en: 'In which country was the pineapple "Hawaiian" pizza invented?' }, a: { ar: 'كندا', en: 'Canada' } },
  { q: { ar: 'ما الحرف الإنجليزي الوحيد الذي لا يظهر في اسم أي ولاية أمريكية؟', en: 'Which is the only letter that appears in no US state name?' }, a: { ar: 'Q', en: 'Q' } },
  { q: { ar: 'ما الاسم القديم لفاكهة الكيوي؟', en: 'What was the kiwi fruit originally called?' }, a: { ar: 'عنب الثعلب الصيني', en: 'Chinese gooseberry' }, alt: ['chinese gooseberry', 'عنب الثعلب'] },
  { q: { ar: 'ماذا يخزن الجمل في سنامه؟', en: 'What does a camel store in its hump?' }, a: { ar: 'الدهون', en: 'Fat' }, alt: ['دهون', 'الشحم', 'شحم', 'fats'] },
  { q: { ar: 'ما لون جلد الدب القطبي تحت فروه الأبيض؟', en: "What colour is a polar bear's skin under its fur?" }, a: { ar: 'أسود', en: 'Black' }, alt: ['الاسود'] },
  { q: { ar: 'كم قلباً للأخطبوط؟', en: 'How many hearts does an octopus have?' }, a: { ar: '3', en: '3' }, alt: ['ثلاثة', 'ثلاث', 'three'] },
  { q: { ar: 'ماذا يصنع الشخص الذي يعمل "ليكسيكوغرافر"؟', en: 'What does a lexicographer make?' }, a: { ar: 'القواميس', en: 'Dictionaries' }, alt: ['قاموس', 'معاجم', 'المعاجم', 'dictionary'] },
  { q: { ar: 'أين نشأت الأرقام التي يسميها الغرب "الأرقام العربية"؟', en: 'Where did the digits the West calls "Arabic numerals" originate?' }, a: { ar: 'الهند', en: 'India' } },
  { q: { ar: 'ما الصوت الذي تصدره الزرافات غالباً في الليل؟', en: 'What sound do giraffes mostly make at night?' }, a: { ar: 'الهمهمة', en: 'Humming' }, alt: ['همهمة', 'طنين', 'hum', 'hums'] },
  { q: { ar: 'ما الفاكهة الوطنية لبنغلاديش، وهي أكبر ثمرة تنمو على شجرة في العالم؟', en: 'What fruit is the national fruit of Bangladesh AND the biggest tree fruit in the world?' }, a: { ar: 'الجاكفروت', en: 'Jackfruit' }, alt: ['جاك فروت', 'الكاكايا', 'jack fruit'] },
  { q: { ar: 'سُمّيت رياضة الريشة الطائرة "بادمنتون" على اسم ماذا؟', en: 'The sport of badminton is named after what?' }, a: { ar: 'قصر بادمنتون', en: 'Badminton House' }, alt: ['بيت بادمنتون', 'قصر', 'a house', 'an estate', 'badminton house'] },
  { q: { ar: 'ما أول منتج تم مسحه بالباركود في متجر عام 1974؟', en: 'What was the first product ever scanned with a barcode in a shop (1974)?' }, a: { ar: 'علبة علكة', en: 'A pack of chewing gum' }, alt: ['علكة', 'علك', 'chewing gum', 'gum'] },
  { q: { ar: 'غلاف الفقاعات "Bubble Wrap" اختُرع في الأصل ليكون ماذا؟', en: 'Bubble Wrap was originally invented to be what?' }, a: { ar: 'ورق جدران', en: 'Textured wallpaper' }, alt: ['ورق الجدران', 'ورق حائط', 'wallpaper'] },
  { q: { ar: 'ما الكوكب الذي يدور حول نفسه وهو مائل على جنبه تقريباً؟', en: 'Which planet spins almost on its side?' }, a: { ar: 'أورانوس', en: 'Uranus' }, alt: ['اورانوس'] },
  { q: { ar: 'ما الحيوان الثديي الذي يبيض وله منقار يشبه منقار البطة؟', en: 'Which egg-laying mammal has a duck-like bill?' }, a: { ar: 'خلد الماء', en: 'Platypus' }, alt: ['منقار البط', 'البلاتيبوس', 'the platypus'] },
  { q: { ar: 'ما الرياضة الوطنية الصيفية الرسمية لكندا؟', en: "What is Canada's official national summer sport?" }, a: { ar: 'اللاكروس', en: 'Lacrosse' }, alt: ['لاكروس'] },
  { q: { ar: 'أي فاكهة كانت تُلقب قديماً في أوروبا بـ"تفاحة الحب"؟', en: 'Which fruit was once nicknamed the "love apple" in Europe?' }, a: { ar: 'الطماطم', en: 'Tomato' }, alt: ['طماطم', 'البندورة', 'بندورة', 'tomatoes'] },
  { q: { ar: 'ما اسم الخوف من التصاق زبدة الفول السوداني بسقف الفم؟', en: 'What is the fear of peanut butter sticking to the roof of your mouth called?' }, a: { ar: 'أراكيبوتيروفوبيا', en: 'Arachibutyrophobia' }, alt: ['arachibutyrophobia'] },
  { q: { ar: 'ما اسم أول حيوان ثديي تم استنساخه من خلية بالغة؟', en: 'What was the name of the first mammal cloned from an adult cell?' }, a: { ar: 'النعجة دوللي', en: 'Dolly the sheep' }, alt: ['دوللي', 'دولي', 'dolly'] },
  { q: { ar: 'أي دولة أهدت تمثال الحرية للولايات المتحدة؟', en: 'Which country gave the Statue of Liberty to the USA?' }, a: { ar: 'فرنسا', en: 'France' } },
  { q: { ar: 'ما الدولة التي فيها أكبر عدد من الأهرامات في العالم؟', en: 'Which country has the most pyramids in the world?' }, a: { ar: 'السودان', en: 'Sudan' } },
  { q: { ar: 'ما كان لون تمثال الحرية عندما افتُتح أول مرة؟', en: 'What colour was the Statue of Liberty when it was first unveiled?' }, a: { ar: 'نحاسي', en: 'Copper brown' }, alt: ['بني', 'النحاسي', 'copper', 'brown'] },
  { q: { ar: 'ما الكائن المجهري الذي نجا بعد تعريضه لفراغ الفضاء الخارجي؟', en: 'Which microscopic animal has survived exposure to outer space?' }, a: { ar: 'دب الماء', en: 'Tardigrade' }, alt: ['بطيء الخطو', 'دببة الماء', 'water bear', 'tardigrades'] },
  { q: { ar: 'ما اسم الكلبة التي كانت أول حيوان يدور حول الأرض عام 1957؟', en: 'What was the name of the dog that became the first animal to orbit Earth (1957)?' }, a: { ar: 'لايكا', en: 'Laika' } },
  { q: { ar: 'عن ماذا كان أول فيديو نُشر على يوتيوب؟', en: 'What was the very first YouTube video about?' }, a: { ar: 'زيارة حديقة حيوان', en: 'A trip to the zoo' }, alt: ['حديقة الحيوان', 'حديقة حيوانات', 'الفيلة', 'zoo', 'the zoo', 'elephants'] },
  { q: { ar: 'أي مدينة عربية تُلقب بـ"عروس البحر الأحمر"؟', en: 'Which Arab city is nicknamed "the Bride of the Red Sea"?' }, a: { ar: 'جدة', en: 'Jeddah' }, alt: ['جده', 'jiddah'] },
  { q: { ar: 'ما الكائن الذي سُجّل كأطول الحيوانات عمراً بعمر تجاوز 500 سنة؟', en: 'Which animal holds the record as the longest-lived, at over 500 years?' }, a: { ar: 'محار الكوهوج', en: 'A quahog clam' }, alt: ['محار', 'المحار', 'صدفة', 'clam', 'quahog'] },
  { q: { ar: 'ما القارة الوحيدة التي لا تعيش فيها أي زواحف؟', en: 'Which is the only continent with no reptiles?' }, a: { ar: 'القارة القطبية الجنوبية', en: 'Antarctica' }, alt: ['انتاركتيكا', 'القطب الجنوبي', 'أنتاركتيكا'] },
  { q: { ar: 'على ماذا بُني فندق برج العرب في دبي؟', en: 'What was the Burj Al Arab hotel in Dubai built on?' }, a: { ar: 'جزيرة صناعية', en: 'An artificial island' }, alt: ['جزيرة اصطناعية', 'جزيرة', 'artificial island', 'island'] },
  { q: { ar: 'في أي دولة استُبعدت إبل من مسابقة جمال لأنها حُقنت بالبوتوكس؟', en: 'In which country were camels disqualified from a beauty contest for Botox?' }, a: { ar: 'السعودية', en: 'Saudi Arabia' }, alt: ['المملكة العربية السعودية', 'saudi'] },
  { q: { ar: 'ما الحيوان المرسوم على علم سريلانكا؟', en: 'Which animal appears on the flag of Sri Lanka?' }, a: { ar: 'أسد', en: 'A lion' }, alt: ['الأسد', 'lion'] },
  { q: { ar: 'ما الاسم الأصلي لمكعب روبيك عند اختراعه؟', en: "What was the Rubik's Cube originally called?" }, a: { ar: 'المكعب السحري', en: 'Magic Cube' }, alt: ['مكعب سحري', 'the magic cube'] },
  { q: { ar: 'ما الغاز الذي يجعل صوتك غليظاً جداً إذا استنشقته؟', en: 'Which gas makes your voice sound very deep if you inhale it?' }, a: { ar: 'سادس فلوريد الكبريت', en: 'Sulfur hexafluoride' }, alt: ['sf6', 'sulphur hexafluoride'] },
  { q: { ar: 'ما البلد الذي اخترع الورق؟', en: 'Which country invented paper?' }, a: { ar: 'الصين', en: 'China' } },
  { q: { ar: 'ما الحيوان الذي ينام واقفاً ويحلم مستلقياً؟', en: 'Which animal sleeps standing up but dreams lying down?' }, a: { ar: 'الحصان', en: 'The horse' }, alt: ['حصان', 'horse'] },
  { q: { ar: 'ما الدولة التي يوجد فيها أطول اسم عاصمة في العالم؟', en: 'Which country has the longest capital city name?' }, a: { ar: 'تايلاند', en: 'Thailand' }, alt: ['تايلند'] },
  { q: { ar: 'ما المادة التي تتكون منها أظافر الإنسان؟', en: 'What are human nails made of?' }, a: { ar: 'الكيراتين', en: 'Keratin' }, alt: ['كيراتين', 'keratin'] },
  { q: { ar: 'أي كوكب يُلفظ اسمه على أنه الأسخن في المجموعة الشمسية؟', en: 'Which planet is the hottest in the solar system?' }, a: { ar: 'الزهرة', en: 'Venus' }, alt: ['كوكب الزهرة', 'فينوس'] },
  { q: { ar: 'ماذا يُسمّى الخوف من الأماكن المغلقة؟', en: 'What is the fear of enclosed spaces called?' }, a: { ar: 'رهاب الأماكن المغلقة', en: 'Claustrophobia' }, alt: ['كلاستروفوبيا', 'claustrophobia'] },
  { q: { ar: 'ما أسرع عضلة في جسم الإنسان؟', en: 'What is the fastest muscle in the human body?' }, a: { ar: 'عضلة الجفن', en: 'The eyelid muscle' }, alt: ['الجفن', 'عضلة العين', 'eyelid'] },
  { q: { ar: 'ما اللون الذي يراه الإنسان أولاً عند الاستيقاظ في الظلام؟', en: 'Which colour does the human eye detect best in low light?' }, a: { ar: 'الأخضر', en: 'Green' }, alt: ['اخضر', 'green'] },
  { q: { ar: 'كم ضلعاً في جسم الإنسان البالغ؟', en: 'How many ribs does an adult human have?' }, a: { ar: '24', en: '24' }, alt: ['٢٤', 'أربعة وعشرون', 'twenty four'] },
  { q: { ar: 'ما الطائر الذي يستطيع الطيران للخلف؟', en: 'Which bird can fly backwards?' }, a: { ar: 'الطنان', en: 'The hummingbird' }, alt: ['طائر الطنان', 'هامنق بيرد', 'hummingbird'] },
  { q: { ar: 'ما أكبر عضو في جسم الإنسان؟', en: 'What is the largest organ in the human body?' }, a: { ar: 'الجلد', en: 'The skin' }, alt: ['جلد', 'skin'] },
  { q: { ar: 'في أي دولة اختُرع الورق لأول مرة؟', en: 'In which country was paper first invented?' }, a: { ar: 'الصين', en: 'China' }, alt: ['صين'] },
  { q: { ar: 'ما الحيوان الذي لا يستطيع إخراج لسانه؟', en: 'Which animal cannot stick out its tongue?' }, a: { ar: 'التمساح', en: 'The crocodile' }, alt: ['تمساح', 'crocodile'] },
  { q: { ar: 'ما الشيء الذي يصبح أثقل كلما جفّ؟', en: 'What gets heavier the drier it gets?' }, a: { ar: 'الإسفنج المبلل بالملح', en: 'A salt sponge' }, alt: ['الاسفنج', 'اسفنج'] },
  { q: { ar: 'كم مرة ينبض قلب الإنسان في اليوم تقريباً؟', en: 'Roughly how many times does a human heart beat per day?' }, a: { ar: 'مئة ألف', en: 'About 100,000' }, alt: ['100000', '١٠٠٠٠٠', 'مية الف'] },
  { q: { ar: 'ما اسم أكبر صحراء باردة في العالم؟', en: 'What is the largest cold desert in the world?' }, a: { ar: 'القطب الجنوبي', en: 'Antarctica' }, alt: ['انتاركتيكا', 'أنتاركتيكا', 'antarctica'] },
  { q: { ar: 'أي حرف عربي هو الأكثر استخداماً في اللغة العربية؟', en: 'Which Arabic letter is the most used in Arabic?' }, a: { ar: 'الألف', en: 'Alif' }, alt: ['الف', 'ا', 'alif'] },
  { q: { ar: 'ماذا يحدث لطول الإنسان خلال اليوم؟', en: 'What happens to a human’s height during the day?' }, a: { ar: 'ينقص قليلاً', en: 'It shrinks slightly' }, alt: ['يقصر', 'ينقص', 'يقل', 'shrinks'] },
  { q: { ar: 'ما الحيوان الذي بصمة أنفه فريدة مثل بصمة الإنسان؟', en: 'Which animal has a unique nose print like a human fingerprint?' }, a: { ar: 'الكلب', en: 'The dog' }, alt: ['كلب', 'dog'] },
  { q: { ar: 'كم تستغرق أشعة الشمس للوصول إلى الأرض؟', en: 'How long does sunlight take to reach Earth?' }, a: { ar: 'ثماني دقائق', en: 'About 8 minutes' }, alt: ['8 دقائق', '٨ دقائق', '8 minutes'] },
  { q: { ar: 'ما المشروب الأكثر استهلاكاً في العالم بعد الماء؟', en: 'What is the most consumed drink after water?' }, a: { ar: 'الشاي', en: 'Tea' }, alt: ['شاي', 'tea'] },
  { q: { ar: 'ما اسم المسافة التي يقطعها الضوء في سنة؟', en: 'What is the distance light travels in a year called?' }, a: { ar: 'سنة ضوئية', en: 'A light year' }, alt: ['السنة الضوئية', 'light year'] },
  { q: { ar: 'أي جزء من جسم الإنسان لا يحتوي على أوعية دموية؟', en: 'Which part of the human body has no blood vessels?' }, a: { ar: 'قرنية العين', en: 'The cornea' }, alt: ['القرنية', 'cornea'] },
  { q: { ar: 'ما الحيوان الذي يُعتبر أذكى بعد الإنسان حسب كثير من الدراسات؟', en: 'Which animal is often ranked smartest after humans?' }, a: { ar: 'الدلفين', en: 'The dolphin' }, alt: ['دلفين', 'dolphin'] },
  { q: { ar: 'كم لوناً في قوس قزح؟', en: 'How many colours are in a rainbow?' }, a: { ar: 'سبعة', en: 'Seven' }, alt: ['7', '٧', 'seven'] },
  { q: { ar: 'أي حيوان لديه أطول فترة حمل على الأرض؟', en: 'Which land animal has the longest pregnancy?' }, a: { ar: 'الفيل', en: 'The elephant' }, alt: ['فيل', 'elephant'] },
];

const number = [
  { q: { ar: 'كم عظمة في جسم الإنسان البالغ؟', en: 'How many bones are in an adult human body?' }, a: 206 },
  { q: { ar: 'كم ارتفاع برج خليفة بالمتر؟', en: 'How tall is the Burj Khalifa, in metres?' }, a: 828, unit: { ar: 'م', en: 'm' } },
  { q: { ar: 'كم عدد الدول الأعضاء في جامعة الدول العربية؟', en: 'How many member states are in the Arab League?' }, a: 22 },
  { q: { ar: 'كم دقيقة في الأسبوع الواحد؟', en: 'How many minutes are in one week?' }, a: 10080 },
  { q: { ar: 'في أي سنة غرقت سفينة تايتانيك؟', en: 'In what year did the Titanic sink?' }, a: 1912 },
  { q: { ar: 'كم مفتاحاً في البيانو القياسي؟', en: 'How many keys does a standard piano have?' }, a: 88 },
  { q: { ar: 'كم سرعة الصوت في الهواء تقريباً (متر/ثانية)؟', en: 'Roughly how fast is sound in air (metres per second)?' }, a: 343, unit: { ar: 'م/ث', en: 'm/s' } },
  { q: { ar: 'كم طول نهر النيل تقريباً بالكيلومتر؟', en: 'Roughly how long is the Nile, in km?' }, a: 6650, unit: { ar: 'كم', en: 'km' } },
  { q: { ar: 'كم سنتيمتراً يزداد طول برج إيفل تقريباً في الصيف؟', en: 'About how many centimetres does the Eiffel Tower grow in summer?' }, a: 15, unit: { ar: 'سم', en: 'cm' } },
  { q: { ar: 'كم لغة تقريباً يتحدث بها البشر حول العالم اليوم؟', en: 'About how many languages are spoken in the world today?' }, a: 7000 },
  { q: { ar: 'في أي سنة سقط جدار برلين؟', en: 'In what year did the Berlin Wall fall?' }, a: 1989 },
  { q: { ar: 'كم متوسط المسافة بين الأرض والقمر بالكيلومتر؟', en: 'What is the average Earth–Moon distance, in km?' }, a: 384400, unit: { ar: 'كم', en: 'km' } },
  { q: { ar: 'كم عمق خندق ماريانا تقريباً بالمتر؟', en: 'Roughly how deep is the Mariana Trench, in metres?' }, a: 11000, unit: { ar: 'م', en: 'm' } },
  { q: { ar: 'كم درجة حرارة سطح الشمس تقريباً بالمئوية؟', en: "Roughly how hot is the Sun's surface, in °C?" }, a: 5500, unit: { ar: '°م', en: '°C' } },
  { q: { ar: 'في أي سنة تأسست شركة جوجل؟', en: 'In what year was Google founded?' }, a: 1998 },
  { q: { ar: 'كم مجموع النقاط على حجر النرد العادي؟', en: 'What is the total number of dots on a standard die?' }, a: 21 },
  { q: { ar: 'كم منطقة زمنية في روسيا؟', en: 'How many time zones does Russia have?' }, a: 11 },
  { q: { ar: 'كم ثانية في اليوم الواحد؟', en: 'How many seconds are in one day?' }, a: 86400 },
  { q: { ar: 'كم سنة استمرت "حرب المئة عام" فعلياً؟', en: 'How many years did the "Hundred Years\' War" actually last?' }, a: 116 },
  { q: { ar: 'كم ضلعاً في القفص الصدري للإنسان عادةً؟', en: 'How many ribs does a human usually have in total?' }, a: 24 },
  { q: { ar: 'كم نسبة سطح الأرض المغطاة بالماء تقريباً (%)؟', en: "Roughly what percentage of Earth's surface is water?" }, a: 71, unit: { ar: '%', en: '%' } },
  { q: { ar: 'كم عدد سكان العالم تقريباً بالمليار؟', en: "Roughly what is the world's population, in billions?" }, a: 8, unit: { ar: 'مليار', en: 'billion' } },
  { q: { ar: 'في أي سنة أُطلق أول هاتف آيفون؟', en: 'In what year was the first iPhone released?' }, a: 2007 },
  { q: { ar: 'كم مربعاً على رقعة الشطرنج؟', en: 'How many squares are on a chessboard?' }, a: 64 },
  { q: { ar: 'كم سناً لدى الإنسان البالغ مع ضروس العقل؟', en: 'How many teeth does an adult have, including wisdom teeth?' }, a: 32 },
  { q: { ar: 'كم عدد الخطوط في علم الولايات المتحدة؟', en: 'How many stripes are on the US flag?' }, a: 13 },
  { q: { ar: 'كم عدد لاعبي فريق الرغبي (اتحاد) داخل الملعب؟', en: 'How many players does a rugby union team have on the field?' }, a: 15 },
  { q: { ar: 'كم عدد أرجل الكركند (جراد البحر)؟', en: 'How many legs does a lobster have?' }, a: 10 },
  { q: { ar: 'كم عظمة في يد الإنسان الواحدة (مع الرسغ)؟', en: 'How many bones are in one human hand (including the wrist)?' }, a: 27 },
  { q: { ar: 'كم سرعة الضوء تقريباً بالكيلومتر في الثانية؟', en: 'Roughly what is the speed of light, in km per second?' }, a: 300000, unit: { ar: 'كم/ث', en: 'km/s' } },
  { q: { ar: 'كم عدد دول قارة أفريقيا؟', en: 'How many countries are in Africa?' }, a: 54 },
  { q: { ar: 'كم عدد الدول الأعضاء في الأمم المتحدة؟', en: 'How many member states does the United Nations have?' }, a: 193 },
  { q: { ar: 'كم ارتفاع قمة إيفرست بالمتر؟', en: 'How tall is Mount Everest, in metres?' }, a: 8849, unit: { ar: 'م', en: 'm' } },
  { q: { ar: 'في أي سنة نالت الكويت استقلالها؟', en: 'In what year did Kuwait gain independence?' }, a: 1961 },
  { q: { ar: 'في أي سنة قام اتحاد دولة الإمارات العربية المتحدة؟', en: 'In what year was the United Arab Emirates founded?' }, a: 1971 },
  { q: { ar: 'في أي سنة أقيمت أول ألعاب أولمبية حديثة؟', en: 'In what year were the first modern Olympic Games held?' }, a: 1896 },
  { q: { ar: 'كم عدد سور القرآن الكريم؟', en: 'How many surahs are in the Quran?' }, a: 114 },
  { q: { ar: 'كم حرفاً في الأبجدية الإنجليزية؟', en: 'How many letters are in the English alphabet?' }, a: 26 },
  { q: { ar: 'في أي سنة هبط الإنسان على القمر لأول مرة؟', en: 'In what year did humans first land on the Moon?' }, a: 1969 },
  { q: { ar: 'عند كم درجة فهرنهايت يغلي الماء؟', en: 'At how many degrees Fahrenheit does water boil?' }, a: 212, unit: { ar: '°ف', en: '°F' } },
  { q: { ar: 'كم أقصى سرعة للفهد تقريباً بالكيلومتر/ساعة؟', en: "Roughly what is a cheetah's top speed, in km/h?" }, a: 110, unit: { ar: 'كم/س', en: 'km/h' } },
  { q: { ar: 'كم الطول الكلي لسور الصين العظيم بكل فروعه تقريباً بالكيلومتر؟', en: 'Roughly how long is the Great Wall of China including all branches, in km?' }, a: 21196, unit: { ar: 'كم', en: 'km' } },
  { q: { ar: 'كم درجة في الدائرة الكاملة؟', en: 'How many degrees are in a full circle?' }, a: 360 },
  { q: { ar: 'في أي سنة اقتُرحت شبكة الويب العالمية (WWW)؟', en: 'In what year was the World Wide Web first proposed?' }, a: 1989 },
  { q: { ar: 'كم متراً في الميل الواحد تقريباً؟', en: 'Roughly how many metres are in one mile?' }, a: 1609, unit: { ar: 'م', en: 'm' } },
  { q: { ar: 'كم كان الارتفاع الأصلي للهرم الأكبر في الجيزة بالمتر تقريباً؟', en: 'Roughly how tall was the Great Pyramid of Giza originally, in metres?' }, a: 146, unit: { ar: 'م', en: 'm' } },
  { q: { ar: 'كم قمراً يدور حول كوكب المريخ؟', en: 'How many moons does Mars have?' }, a: 2 },
  { q: { ar: 'كم عنصراً في الجدول الدوري حالياً؟', en: 'How many elements are currently in the periodic table?' }, a: 118 },
  { q: { ar: 'في أي سنة أُعلن توحيد المملكة العربية السعودية باسمها الحالي؟', en: 'In what year was the Kingdom of Saudi Arabia proclaimed under its current name?' }, a: 1932 },
  { q: { ar: 'كم وتراً في الغيتار العادي؟', en: 'How many strings does a standard guitar have?' }, a: 6 },
  { q: { ar: 'كم يبلغ ارتفاع برج إيفل بالأمتار؟', en: 'How tall is the Eiffel Tower in metres?' }, a: 330, unit: { ar: 'م', en: 'm' } },
  { q: { ar: 'كم دولة عضو في الأمم المتحدة؟', en: 'How many member states does the UN have?' }, a: 193, unit: { ar: 'دولة', en: 'countries' } },
  { q: { ar: 'كم يبلغ طول نهر النيل بالكيلومترات؟', en: 'How long is the Nile in kilometres?' }, a: 6650, unit: { ar: 'كم', en: 'km' } },
  { q: { ar: 'كم عدد الأسنان لدى الإنسان البالغ؟', en: 'How many teeth does an adult human have?' }, a: 32, unit: { ar: 'سن', en: 'teeth' } },
  { q: { ar: 'كم درجة حرارة جسم الإنسان الطبيعية بالمئوية؟', en: 'What is normal human body temperature in Celsius?' }, a: 37, unit: { ar: '°م', en: '°C' } },
  { q: { ar: 'كم عدد اللاعبين في فريق كرة السلة داخل الملعب؟', en: 'How many basketball players per team are on court?' }, a: 5, unit: { ar: 'لاعبين', en: 'players' } },
  { q: { ar: 'كم يبلغ عمق أعمق نقطة في المحيط بالأمتار؟', en: 'How deep is the deepest point of the ocean in metres?' }, a: 10935, unit: { ar: 'م', en: 'm' } },
  { q: { ar: 'كم يبلغ وزن قلب الإنسان بالغرامات تقريباً؟', en: 'Roughly how much does a human heart weigh in grams?' }, a: 300, unit: { ar: 'غم', en: 'g' } },
  { q: { ar: 'كم عدد الأبراج الفلكية؟', en: 'How many zodiac signs are there?' }, a: 12, unit: { ar: 'برج', en: 'signs' } },
  { q: { ar: 'كم مساحة المملكة العربية السعودية بالكيلومتر المربع تقريباً؟', en: 'What is the area of Saudi Arabia in square kilometres?' }, a: 2150000, unit: { ar: 'كم²', en: 'km²' } },
  { q: { ar: 'كم عدد ألوان مكعب روبيك؟', en: 'How many colours does a Rubik\'s cube have?' }, a: 6, unit: { ar: 'ألوان', en: 'colours' } },
  { q: { ar: 'كم يبلغ طول سور الصين العظيم بالكيلومترات؟', en: 'How long is the Great Wall of China in kilometres?' }, a: 21196, unit: { ar: 'كم', en: 'km' } },
  { q: { ar: 'كم عدد عيون النحلة؟', en: 'How many eyes does a bee have?' }, a: 5, unit: { ar: 'عيون', en: 'eyes' } },
  { q: { ar: 'كم عدد الدقائق في أسبوع كامل؟', en: 'How many minutes are in a full week?' }, a: 10080, unit: { ar: 'دقيقة', en: 'minutes' } },
  { q: { ar: 'كم عدد حروف الأبجدية العربية؟', en: 'How many letters are in the Arabic alphabet?' }, a: 28, unit: { ar: 'حرف', en: 'letters' } },
  { q: { ar: 'كم سنة يعيش الفيل في المتوسط؟', en: 'How long does an elephant live on average?' }, a: 65, unit: { ar: 'سنة', en: 'years' } },
  { q: { ar: 'كم يوماً يستغرق القمر ليدور حول الأرض؟', en: 'How many days does the Moon take to orbit Earth?' }, a: 27, unit: { ar: 'يوم', en: 'days' } },
  { q: { ar: 'كم عدد أوتار الكمان؟', en: 'How many strings does a violin have?' }, a: 4, unit: { ar: 'أوتار', en: 'strings' } },
  { q: { ar: 'كم يبلغ طول ملعب كرة القدم القياسي بالأمتار؟', en: 'How long is a standard football pitch in metres?' }, a: 105, unit: { ar: 'م', en: 'm' } },
  { q: { ar: 'كم عدد حلقات شعار الألعاب الأولمبية؟', en: 'How many rings are in the Olympic logo?' }, a: 5, unit: { ar: 'حلقات', en: 'rings' } },
];

const blitz = [
  { s: { ar: 'العسل لا يفسد تقريباً مهما طال الزمن.', en: 'Honey basically never spoils.' }, t: true },
  { s: { ar: 'سور الصين العظيم يُرى بالعين المجردة من القمر.', en: 'The Great Wall of China is visible from the Moon with the naked eye.' }, t: false },
  { s: { ar: 'للأخطبوط ثلاثة قلوب.', en: 'An octopus has three hearts.' }, t: true },
  { s: { ar: 'ذاكرة السمكة الذهبية 3 ثوانٍ فقط.', en: 'A goldfish only has a 3-second memory.' }, t: false },
  { s: { ar: 'الموز يُصنّف علمياً من التوت.', en: 'Botanically, bananas are berries.' }, t: true },
  { s: { ar: 'الفراولة تُصنّف علمياً من التوت.', en: 'Botanically, strawberries are berries.' }, t: false },
  { s: { ar: 'يوم كوكب الزهرة أطول من سنته.', en: 'A day on Venus is longer than its year.' }, t: true },
  { s: { ar: 'البرق لا يضرب المكان نفسه مرتين أبداً.', en: 'Lightning never strikes the same place twice.' }, t: false },
  { s: { ar: 'أسماك القرش أقدم على الأرض من الأشجار.', en: 'Sharks are older than trees.' }, t: true },
  { s: { ar: 'الخفافيش عمياء.', en: 'Bats are blind.' }, t: false },
  { s: { ar: 'برج إيفل يصبح أطول قليلاً في الصيف.', en: 'The Eiffel Tower gets slightly taller in summer.' }, t: true },
  { s: { ar: 'الإنسان يستخدم 10% فقط من دماغه.', en: 'Humans only use 10% of their brains.' }, t: false },
  { s: { ar: 'حيوان الكسلان يحبس أنفاسه مدة أطول من الدلفين.', en: 'Sloths can hold their breath longer than dolphins.' }, t: true },
  { s: { ar: 'إيفرست أطول جبل في العالم إذا قيس من القاعدة إلى القمة.', en: 'Everest is the tallest mountain when measured from base to peak.' }, t: false },
  { s: { ar: 'الأرقام "العربية" نشأت أصلاً في الهند.', en: '"Arabic" numerals originally came from India.' }, t: true },
  { s: { ar: 'الجمل يخزن الماء في سنامه.', en: 'Camels store water in their humps.' }, t: false },
  { s: { ar: 'الزهرة أسخن كوكب في المجموعة الشمسية.', en: 'Venus is the hottest planet in the solar system.' }, t: true },
  { s: { ar: 'الصحراء الكبرى أكبر صحراء في العالم.', en: 'The Sahara is the largest desert in the world.' }, t: false },
  { s: { ar: 'الطماطم فاكهة من الناحية العلمية.', en: 'Scientifically, tomatoes are fruits.' }, t: true },
  { s: { ar: 'البطاريق تعيش في القطب الشمالي.', en: 'Penguins live at the North Pole.' }, t: false },
  { s: { ar: 'بعض السلاحف تستطيع التنفس من مؤخرتها.', en: 'Some turtles can breathe through their rear ends.' }, t: true },
  { s: { ar: 'فضلات حيوان الومبت مكعبة الشكل.', en: 'Wombat poop is cube-shaped.' }, t: true },
  { s: { ar: 'أينشتاين رسب في الرياضيات في المدرسة.', en: 'Einstein failed maths at school.' }, t: false },
  { s: { ar: 'الزجاج سائل يتحرك ببطء شديد.', en: 'Glass is a very slow-moving liquid.' }, t: false },
  { s: { ar: 'الحيوان الوطني لاسكتلندا هو اليونيكورن.', en: "Scotland's national animal is the unicorn." }, t: true },
  { s: { ar: 'اللسان فيه مناطق منفصلة لكل طعم.', en: 'The tongue has separate zones for each taste.' }, t: false },
  { s: { ar: 'نابليون كان قصيراً جداً مقارنة بأهل زمانه.', en: 'Napoleon was unusually short for his time.' }, t: false },
  { s: { ar: 'للكوالا بصمات أصابع.', en: 'Koalas have fingerprints.' }, t: true },
  { s: { ar: 'الفيل البالغ يستطيع القفز.', en: 'An adult elephant can jump.' }, t: false },
  { s: { ar: 'كان الجزر بنفسجي اللون قبل أن يصبح برتقالياً.', en: 'Carrots used to be purple before they were orange.' }, t: true },
  { s: { ar: 'التفاح يطفو على الماء.', en: 'Apples float in water.' }, t: true },
  { s: { ar: 'السكر يجعل الأطفال مفرطي النشاط (ثبت علمياً).', en: 'Sugar makes kids hyperactive (proven by science).' }, t: false },
  { s: { ar: 'مجموعة طيور الفلامنغو تُسمّى بالإنجليزية "flamboyance".', en: 'A group of flamingos is called a "flamboyance".' }, t: true },
  { s: { ar: 'الهرم الأكبر يقع في مدينة الأقصر.', en: 'The Great Pyramid is in Luxor.' }, t: false },
  { s: { ar: 'للمريخ قمران.', en: 'Mars has two moons.' }, t: true },
  { s: { ar: 'كوكب الزهرة يدور حول نفسه بعكس اتجاه معظم الكواكب.', en: 'Venus spins in the opposite direction to most planets.' }, t: true },
  { s: { ar: 'الألماس يتكوّن من الفحم.', en: 'Diamonds form from coal.' }, t: false },
  { s: { ar: 'قلب الروبيان موجود في رأسه.', en: "A shrimp's heart is in its head." }, t: true },
  { s: { ar: 'الثيران يغضبها اللون الأحمر.', en: 'Bulls are enraged by the colour red.' }, t: false },
  { s: { ar: 'دم الأخطبوط أزرق.', en: 'Octopus blood is blue.' }, t: true },
  { s: { ar: 'جبل كليمنجارو يقع في كينيا.', en: 'Mount Kilimanjaro is in Kenya.' }, t: false },
  { s: { ar: 'الموز مشعّ بدرجة بسيطة جداً.', en: 'Bananas are very slightly radioactive.' }, t: true },
  { s: { ar: 'البحر الميت أملح من المحيطات.', en: 'The Dead Sea is saltier than the ocean.' }, t: true },
  { s: { ar: 'اليوم على المريخ مساوٍ تماماً ليوم الأرض.', en: 'A day on Mars is exactly as long as a day on Earth.' }, t: false },
  { s: { ar: 'الطائر الطنان يستطيع الطيران إلى الخلف.', en: 'Hummingbirds can fly backwards.' }, t: true },
  { s: { ar: 'النعامة تدفن رأسها في الرمل عند الخوف.', en: 'Ostriches bury their heads in the sand when scared.' }, t: false },
  { s: { ar: 'النحل يتواصل مع بعضه بالرقص.', en: 'Honeybees communicate by dancing.' }, t: true },
  { s: { ar: 'الشمس كوكب.', en: 'The Sun is a planet.' }, t: false },
  { s: { ar: 'الصوت ينتقل في الماء أسرع من الهواء.', en: 'Sound travels faster in water than in air.' }, t: true },
  { s: { ar: 'القارة القطبية الجنوبية هي أصغر قارة.', en: 'Antarctica is the smallest continent.' }, t: false },
  { s: { ar: 'نهر النيل يصب في البحر الأحمر.', en: 'The Nile flows into the Red Sea.' }, t: false },
  { s: { ar: 'القرش يُصنّف من الأسماك.', en: 'Sharks are fish.' }, t: true },
  { s: { ar: 'الحيتان تُصنّف من الأسماك.', en: 'Whales are fish.' }, t: false },
  { s: { ar: 'لا توجد في الكويت أنهار دائمة.', en: 'Kuwait has no permanent rivers.' }, t: true },
  { s: { ar: 'القاهرة عاصمة المغرب.', en: 'Cairo is the capital of Morocco.' }, t: false },
  { s: { ar: 'الرياض عاصمة المملكة العربية السعودية.', en: 'Riyadh is the capital of Saudi Arabia.' }, t: true },
  { s: { ar: 'للمريخ حلقات مثل زحل.', en: 'Mars has rings like Saturn.' }, t: false },
  { s: { ar: 'أعلى قمة في أفريقيا هي جبل كليمنجارو.', en: "Kilimanjaro is Africa's highest peak." }, t: true },
  { s: { ar: 'العسل لا يفسد أبداً إذا حُفظ جيداً.', en: 'Honey never spoils if stored properly.' }, t: true },
  { s: { ar: 'الخفافيش عمياء تماماً.', en: 'Bats are completely blind.' }, t: false },
  { s: { ar: 'جدار الصين العظيم يُرى بالعين المجردة من الفضاء.', en: 'The Great Wall of China is visible from space with the naked eye.' }, t: false },
  { s: { ar: 'الموز نبات عشبي وليس شجرة.', en: 'The banana plant is a herb, not a tree.' }, t: true },
  { s: { ar: 'الأخطبوط له دم أزرق.', en: 'Octopuses have blue blood.' }, t: true },
  { s: { ar: 'القلب البشري ينبض حوالي مئة ألف مرة يومياً.', en: 'The human heart beats around 100,000 times a day.' }, t: true },
  { s: { ar: 'كوكب المشتري هو الأكبر في المجموعة الشمسية.', en: 'Jupiter is the largest planet in the solar system.' }, t: true },
  { s: { ar: 'الذهب معدن قابل للطرق لدرجة أن غراماً واحداً يُمد لمسافة كيلومتر.', en: 'One gram of gold can be stretched into a wire a kilometre long.' }, t: true },
  { s: { ar: 'الحرباء تغيّر لونها لتطابق أي خلفية.', en: 'Chameleons change colour to match any background.' }, t: false },
  { s: { ar: 'الماء النقي موصل جيد للكهرباء.', en: 'Pure water is a good conductor of electricity.' }, t: false },
  { s: { ar: 'اللسان البشري يتكون من عدة عضلات وليس عضلة واحدة.', en: 'The human tongue is made of several muscles, not one.' }, t: true },
  { s: { ar: 'القرش يستطيع شمّ قطرة دم من مسافة كيلومترات.', en: 'Sharks can smell a drop of blood from kilometres away.' }, t: false },
  { s: { ar: 'الزرافة لديها نفس عدد فقرات الرقبة التي لدى الإنسان.', en: 'A giraffe has the same number of neck vertebrae as a human.' }, t: true },
  { s: { ar: 'الشمس صفراء اللون في الحقيقة.', en: 'The Sun is actually yellow.' }, t: false },
  { s: { ar: 'الفراشة تتذوق الطعام بأقدامها.', en: 'Butterflies taste with their feet.' }, t: true },
  { s: { ar: 'الإنسان يستخدم عشرة بالمئة فقط من دماغه.', en: 'Humans use only ten percent of their brain.' }, t: false },
  { s: { ar: 'المعدة تفرز طبقة مخاطية جديدة لتحمي نفسها من حمضها.', en: 'The stomach makes a fresh mucus lining to protect itself from its own acid.' }, t: true },
  { s: { ar: 'القهوة تُزرع أصلاً في البرازيل قبل أي مكان آخر.', en: 'Coffee was originally grown in Brazil before anywhere else.' }, t: false },
  { s: { ar: 'النمل لا ينام مثل البشر.', en: 'Ants do not sleep the way humans do.' }, t: true },
  { s: { ar: 'عين النعامة أكبر من دماغها.', en: "An ostrich's eye is bigger than its brain." }, t: true },
  { s: { ar: 'الدلافين تنام بنصف دماغها فقط في كل مرة.', en: 'Dolphins sleep with only half their brain at a time.' }, t: true },
  { s: { ar: 'الطماطم تُصنّف فاكهة من الناحية النباتية.', en: 'Botanically, a tomato is a fruit.' }, t: true },
  { s: { ar: 'سور الصين العظيم بُني خلال سنة واحدة.', en: 'The Great Wall of China was built in a single year.' }, t: false },
  { s: { ar: 'القطط ترى الألوان تماماً كما يراها البشر.', en: 'Cats see colours exactly the way humans do.' }, t: false },
  { s: { ar: 'الأرض تكمل دورتها حول الشمس في 365 يوماً تقريباً.', en: 'Earth completes its orbit around the Sun in about 365 days.' }, t: true },
];

// "Who's most likely…?" prompts — players vote for each other.
const likely = [
  { ar: 'مين أكثر واحد ممكن ينام في عرس؟', en: "Who's most likely to fall asleep at a wedding?" },
  { ar: 'مين يضيّع مفاتيحه كل يوم؟', en: "Who's most likely to lose their keys every single day?" },
  { ar: 'مين أول واحد بيهرب لو شفنا صرصور طاير؟', en: "Who's the first to run if a flying cockroach shows up?" },
  { ar: 'مين يطلب أكل وياكل من صحون الكل؟', en: "Who's most likely to order food and then eat from everyone's plate?" },
  { ar: 'مين يصير مشهور على السوشال ميديا بالغلط؟', en: "Who's most likely to go viral by accident?" },
  { ar: 'مين يرد على المسج بعد أسبوع؟', en: "Who's most likely to reply to a message a week later?" },
  { ar: 'مين يضحك في أسوأ وقت ممكن؟', en: "Who's most likely to laugh at the worst possible moment?" },
  { ar: 'مين ممكن يصير مليونير؟', en: "Who's most likely to become a millionaire?" },
  { ar: 'مين يتأخر حتى على موعد هو اللي حدده؟', en: "Who's most likely to be late to their own plans?" },
  { ar: 'مين يقدر يقنع أي أحد بأي شي؟', en: "Who could convince anyone of anything?" },
  { ar: 'مين يصوّر الأكل قبل ما ياكله دايماً؟', en: "Who always photographs their food before eating?" },
  { ar: 'مين يختار يعيش في المخيّم بالبر للأبد؟', en: "Who would happily live in a desert camp forever?" },
  { ar: 'مين يضيع في مول يعرفه زين؟', en: "Who's most likely to get lost in a mall they know well?" },
  { ar: 'مين يسولف ساعة عن شي صار في دقيقة؟', en: "Who takes an hour to tell a one-minute story?" },
  { ar: 'مين يشتري شي ما يحتاجه بس لأن عليه خصم؟', en: "Who buys useless stuff just because it's on sale?" },
  { ar: 'مين يفوز في برنامج مسابقات على التلفزيون؟', en: "Who's most likely to win a TV quiz show?" },
  { ar: 'مين يبكي وهو يطالع فيلم كرتون؟', en: "Who's most likely to cry during a cartoon movie?" },
  { ar: 'مين يصحى الساعة 5 الفجر برضاه؟', en: "Who wakes up at 5am on purpose?" },
  { ar: 'مين ينسى عيد ميلاد أقرب أصحابه؟', en: "Who's most likely to forget their best friend's birthday?" },
  { ar: 'مين يطبخ أكلة غريبة ويحلف إنها لذيذة؟', en: "Who cooks something weird and swears it's delicious?" },
  { ar: 'مين يتهاوش مع الـ GPS؟', en: "Who's most likely to argue with the GPS?" },
  { ar: 'مين يكلّم نفسه بصوت عالي؟', en: "Who talks to themselves out loud?" },
  { ar: 'مين يدوّر جواله وهو في يده؟', en: "Who searches for their phone while holding it?" },
  { ar: 'مين يصير رئيس شركة كبيرة؟', en: "Who's most likely to become CEO of a big company?" },
  { ar: 'مين يغني في السيارة بأعلى صوته؟', en: "Who sings at full volume in the car?" },
  { ar: 'مين يشرب قهوة أكثر من الماي؟', en: "Who drinks more coffee than water?" },
  { ar: 'مين يقرأ المسج ويسوي نفسه ما شافه؟', en: "Who reads a message and pretends they didn't?" },
  { ar: 'مين يضحك على نكتته قبل ما يكملها؟', en: "Who laughs at their own joke before finishing it?" },
  { ar: 'مين يقدر يعيش أسبوع كامل بدون جوال؟', en: "Who could survive a whole week without a phone?" },
  { ar: 'مين يسافر بدون أي تخطيط؟', en: "Who's most likely to travel with zero planning?" },
  { ar: 'مين يتبنّى عشر قطاوة؟', en: "Who's most likely to adopt ten cats?" },
  { ar: 'مين يفتح الثلاجة يطالع فيها ويسكرها بدون ما ياخذ شي؟', en: "Who opens the fridge, stares, and closes it without taking anything?" },
  { ar: 'مين أفضل كذّاب في هاللعبة؟', en: "Who's the best liar in this game?" },
  { ar: 'مين ينسى ليش دخل الغرفة؟', en: "Who forgets why they walked into a room?" },
  { ar: 'مين يصير أول واحد في الطابور قبل ما يفتح المحل؟', en: "Who's first in line before the shop even opens?" },
  { ar: 'مين يرسل رسالة صوتية مدتها 5 دقايق؟', en: "Who sends 5-minute voice notes?" },
  { ar: 'مين يطلب نفس الأكل كل مرة بدون ما يقرأ المنيو؟', en: "Who orders the same food every time without reading the menu?" },
  { ar: 'مين ينسى اسم أحد بعد ثانيتين من التعارف؟', en: 'Who forgets a name two seconds after being introduced?' },
  { ar: 'مين يرد على كل شي بميم؟', en: 'Who replies to everything with a meme?' },
  { ar: 'مين أكثر واحد يتأخر على الطيارة؟', en: 'Who is most likely to almost miss a flight?' },
  { ar: 'مين يشتري قهوة بره وعنده مكينة بالبيت؟', en: 'Who buys coffee out while owning a machine at home?' },
  { ar: 'مين يحفظ أرقام الجوالات غيب؟', en: 'Who still remembers phone numbers by heart?' },
  { ar: 'مين يضيع بجوقل ماب وهو بحيّه؟', en: 'Who gets lost on Google Maps in their own neighbourhood?' },
  { ar: 'مين يبدأ دايت كل يوم اثنين؟', en: 'Who starts a diet every single Monday?' },
  { ar: 'مين يعرف كل أسرار الشلة؟', en: 'Who knows everyone’s secrets?' },
  { ar: 'مين ياخذ أطول وقت يجهز للخروج؟', en: 'Who takes the longest to get ready?' },
  { ar: 'مين يجادل حتى لو يعرف إنه غلطان؟', en: 'Who argues even when they know they are wrong?' },
  { ar: 'مين ينسى شاحن جواله بكل مكان يروحه؟', en: 'Who leaves their charger behind everywhere they go?' },
  { ar: 'مين يصير أول واحد ينام بالسفرة؟', en: 'Who falls asleep first on a trip?' },
  { ar: 'مين يحاول يصلح شي ويخربه أكثر؟', en: 'Who tries to fix something and makes it worse?' },
  { ar: 'مين يشرب قهوته باردة لأنه نساها؟', en: 'Who drinks cold coffee because they forgot about it?' },
  { ar: 'مين يعيد نفس القصة لنفس الأشخاص؟', en: 'Who retells the same story to the same people?' },
  { ar: 'مين يختار الفلم وبعدين ينام فيه؟', en: 'Who picks the movie and then sleeps through it?' },
  { ar: 'مين أكثر واحد يستخدم الإيموجي بكثرة؟', en: 'Who overuses emojis the most?' },
  { ar: 'مين يقدر يسولف مع أي شخص غريب؟', en: 'Who can strike up a chat with any stranger?' },
  { ar: 'مين يحجز موعد ويلغيه بآخر لحظة؟', en: 'Who books plans then cancels at the last minute?' },
];

// Emoji decode — pick what the emojis mean.
const E = (e, ar, en, ...d) => ({ e, a: { ar, en }, d: d.map(([dar, den]) => ({ ar: dar, en: den })) });
const emoji = [
  E('🌧️🌈', 'قوس قزح', 'Rainbow', ['عاصفة', 'Storm'], ['غيمة', 'Cloud'], ['شمسية', 'Umbrella']),
  E('⭐🐟', 'نجم البحر', 'Starfish', ['سمكة ذهبية', 'Goldfish'], ['قنديل البحر', 'Jellyfish'], ['حوت', 'Whale']),
  E('🐝🍯', 'عسل', 'Honey', ['سكر', 'Sugar'], ['تمر', 'Dates'], ['حليب', 'Milk']),
  E('🔥🚒', 'رجل إطفاء', 'Firefighter', ['ضابط شرطة', 'Police officer'], ['طباخ مطعم', 'Restaurant chef'], ['قائد طائرة', 'Airline pilot']),
  E('🐪🏁', 'سباق الهجن', 'Camel race', ['سباق الخيل', 'Horse racing'], ['رالي صحراوي', 'Desert rally'], ['رحلة برية', 'Desert trip']),
  E('🍿🎬', 'سينما', 'Cinema', ['مسرح', 'Theatre'], ['تلفزيون', 'TV'], ['حفلة', 'Party']),
  E('🧊🏔️', 'جبل جليدي', 'Iceberg', ['بركان خامد', 'Dormant volcano'], ['ثلاجة كبيرة', 'Large fridge'], ['فصل الشتاء', 'Wintertime']),
  E('✈️🏝️', 'إجازة', 'Vacation', ['دوام', 'Work shift'], ['سفينة', 'Ship'], ['مطعم', 'Restaurant']),
  E('🦷🧚', 'جنية الأسنان', 'Tooth fairy', ['طبيب أسنان', 'Dentist'], ['فرشاة أسنان', 'Toothbrush'], ['ساحرة شريرة', 'Wicked witch']),
  E('🌊🏄', 'ركوب الأمواج', 'Surfing', ['السباحة الحرة', 'Freestyle swimming'], ['الغوص العميق', 'Deep diving'], ['صيد الأسماك', 'Fishing trip']),
  E('🐍🪜', 'السلم والثعبان', 'Snakes and ladders', ['لعبة الشطرنج', 'A game of chess'], ['أحجار الدومينو', 'Dominoes'], ['ورق البلوت', 'Baloot cards']),
  E('🎂🕯️', 'عيد ميلاد', 'Birthday', ['حفل زواج', 'A wedding'], ['حفل تخرّج', 'Graduation'], ['عشاء عائلي', 'Family dinner']),
  E('🌵🏜️', 'صحراء', 'Desert', ['غابة', 'Forest'], ['شاطئ', 'Beach'], ['جبل', 'Mountain']),
  E('🕷️🕸️', 'شبكة عنكبوت', 'Spider web', ['شبكة صيّاد', 'Fishing net'], ['شبكة الإنترنت', 'The internet'], ['عش العصافير', 'A bird nest']),
  E('👑🦁', 'ملك الغابة', 'King of the jungle', ['سيرك متنقل', 'Travelling circus'], ['نمر مفترس', 'A fierce tiger'], ['قصر الملك', 'The royal palace']),
  E('⏰😴', 'زر الغفوة', 'Snooze button', ['ساعة يد', 'Wristwatch'], ['ليلة أرق', 'Sleepless night'], ['ديك الصباح', 'Morning rooster']),
  E('🌍🔥', 'الاحتباس الحراري', 'Global warming', ['انفجار بركاني', 'Volcanic eruption'], ['موجة حر شديدة', 'A brutal heatwave'], ['سقوط نيزك ضخم', 'A meteor strike']),
  E('🥶🧣', 'برد', 'Cold weather', ['موجة حر', 'Summer heatwave'], ['مطر غزير', 'Heavy rainfall'], ['عاصفة غبار', 'A dust storm']),
  E('🐘💭', 'ذاكرة الفيل', "Elephant's memory", ['حلم غريب', 'A vivid dream'], ['فكرة لامعة', 'A bright idea'], ['حديقة حيوان', 'The city zoo']),
  E('🧠⚡', 'عصف ذهني', 'Brainstorm', ['صداع نصفي', 'A migraine'], ['تيار كهربائي', 'Electric current'], ['نوم عميق', 'Deep sleep']),
  E('🌽💥', 'فشار', 'Popcorn', ['ذرة', 'Corn'], ['ألعاب نارية', 'Fireworks'], ['خبز', 'Bread']),
  E('🐟🍚', 'سوشي', 'Sushi', ['كبسة', 'Kabsa'], ['شوربة', 'Soup'], ['معكرونة', 'Pasta']),
  E('🍚🍗🌶️', 'كبسة', 'Kabsa', ['سوشي', 'Sushi'], ['شاورما', 'Shawarma'], ['بيتزا', 'Pizza']),
  E('💍❓', 'طلب زواج', 'Marriage proposal', ['خاتم ذهب', 'A gold ring'], ['سؤال صعب', 'A hard question'], ['يوم العيد', 'Eid day']),
  E('🚗💨🌀', 'تفحيط', 'Drifting', ['سباق', 'Race'], ['زحمة', 'Traffic jam'], ['غسيل سيارات', 'Car wash']),
  E('🐫🥛', 'حليب ناقة', 'Camel milk', ['لبن رايب', 'Buttermilk'], ['حليب بقر', 'Cow milk'], ['شاي بحليب', 'Milk tea']),
  E('🧞🪔', 'المصباح السحري', 'The magic lamp', ['فانوس رمضان', 'Ramadan lantern'], ['شمعة مضيئة', 'A lit candle'], ['مبخرة عود', 'Incense burner']),
  E('🌴📅', 'تمر', 'Dates', ['موز', 'Banana'], ['تقويم', 'Calendar'], ['جوز هند', 'Coconut']),
  E('❄️⛄', 'رجل ثلج', 'Snowman', ['ثلاجة', 'Freezer'], ['آيسكريم', 'Ice cream'], ['غيمة', 'Cloud']),
  E('🛋️📺🥱', 'يوم كسل', 'A lazy day', ['يوم سفر', 'A travel day'], ['يوم تمرين', 'A workout day'], ['يوم دوام', 'A workday']),
  E('🦉🌙', 'سهران', 'Night owl', ['حكيم', 'Wise one'], ['صاحي بدري', 'Early bird'], ['صياد', 'Hunter']),
  E('🍋🥤', 'ليمونادة', 'Lemonade', ['شاي مثلج', 'Iced tea'], ['قهوة باردة', 'Iced coffee'], ['حليب بارد', 'Cold milk']),
  E('🎮🌙☕', 'سهرة قيمز', 'Gaming all-nighter', ['دوام ليلي', 'A night shift'], ['نوم بدري', 'An early night'], ['رحلة طويلة', 'A long trip']),
  E('📱🔋😱', 'البطارية خلصت', 'Dead battery', ['جوال جديد', 'A new phone'], ['رسالة مهمة', 'An urgent text'], ['مكالمة طويلة', 'A long call']),
  E('🌙🍽️', 'سحور', 'Suhoor', ['عشاء متأخر', 'A late dinner'], ['فطور الصباح', 'Morning breakfast'], ['وجبة خفيفة', 'A light snack']),
  E('🧂🌊', 'ماء مالح', 'Salt water', ['ماء عذب', 'Fresh water'], ['عصير ليمون', 'Lemon juice'], ['شاي بالنعناع', 'Mint tea']),
  E('📚🦉', 'مذاكرة ليلية', 'Late-night study', ['نوم مبكر', 'An early night'], ['رحلة مدرسية', 'A school trip'], ['حصة رياضة', 'A gym class']),
  E('🏜️⛺', 'كشتة', 'A desert camp', ['رحلة بحرية', 'A boat trip'], ['نزهة حديقة', 'A park picnic'], ['سهرة منزل', 'A house party']),
  E('⚽🥅', 'هدف', 'A goal', ['ركلة جزاء', 'A penalty kick'], ['بطاقة حمراء', 'A red card'], ['ضربة ركنية', 'A corner kick']),
  E('🎣🐠', 'صيد سمك', 'Fishing', ['غوص حر', 'Free diving'], ['ركوب قارب', 'Boat riding'], ['سباحة بحر', 'Sea swimming']),
  E('🍯🐻', 'دب يحب العسل', 'A honey-loving bear', ['نحلة عاملة', 'A worker bee'], ['خلية نحل', 'A beehive'], ['غابة كثيفة', 'A dense forest']),
  E('🚗🔑', 'رخصة قيادة', 'A driving licence', ['موقف سيارة', 'A parking spot'], ['ورشة صيانة', 'A repair shop'], ['محطة بنزين', 'A petrol station']),
  E('💻🐛', 'خطأ برمجي', 'A software bug', ['شبكة سريعة', 'A fast network'], ['جهاز جديد', 'A new device'], ['برنامج مجاني', 'Free software']),
  E('🌡️🤒', 'حرارة مرتفعة', 'A fever', ['صداع بسيط', 'A mild headache'], ['برد شديد', 'A bad cold'], ['تعب عام', 'General fatigue']),
  E('🧳✈️', 'حقيبة سفر', 'A travel bag', ['غرفة فندق', 'A hotel room'], ['جواز سفر', 'A passport'], ['تذكرة طيران', 'A plane ticket']),
  E('🎤👏', 'حفلة غنائية', 'A concert', ['مسرح صامت', 'A silent play'], ['ندوة علمية', 'A seminar'], ['مباراة كرة', 'A football match']),
  E('🍉🌞', 'صيف حار', 'A hot summer', ['شتاء بارد', 'A cold winter'], ['ربيع معتدل', 'A mild spring'], ['خريف ممطر', 'A rainy autumn']),
  E('🐟🌊🍚', 'سيّادية', 'Sayadieh', ['كبسة لحم', 'Meat kabsa'], ['مندي دجاج', 'Chicken mandi'], ['مقلوبة خضار', 'Veg maqluba']),
  E('🕌🌙', 'رمضان', 'Ramadan', ['عيد الفطر', 'Eid al-Fitr'], ['موسم الحج', 'Hajj season'], ['ليلة القدر', 'Laylat al-Qadr']),
  E('🧊☕', 'قهوة مثلجة', 'Iced coffee', ['شاي ساخن', 'Hot tea'], ['عصير طازج', 'Fresh juice'], ['حليب دافئ', 'Warm milk']),
  E('🐑🎉', 'عيد الأضحى', 'Eid al-Adha', ['عيد الفطر', 'Eid al-Fitr'], ['يوم وطني', 'A national day'], ['حفل زفاف', 'A wedding party']),
  E('🌵💧', 'صبار', 'A cactus', ['نخلة تمر', 'A date palm'], ['وردة حمراء', 'A red rose'], ['شجرة زيتون', 'An olive tree']),
  E('📖🔍', 'بحث علمي', 'Research', ['قصة قصيرة', 'A short story'], ['رواية طويلة', 'A long novel'], ['مجلة شهرية', 'A monthly magazine']),
  E('🎒🏫', 'أول يوم دراسة', 'First day of school', ['آخر يوم دوام', 'Last day of work'], ['إجازة صيفية', 'Summer holiday'], ['رحلة ترفيهية', 'A fun outing']),
];

// Spy round — everyone but the spy gets the secret word; the spy only sees the category.
const spy = [
  { cat: { ar: 'مكان', en: 'Place' }, w: { ar: 'المطار', en: 'The airport' } },
  { cat: { ar: 'مكان', en: 'Place' }, w: { ar: 'المستشفى', en: 'The hospital' } },
  { cat: { ar: 'مكان', en: 'Place' }, w: { ar: 'المدرسة', en: 'The school' } },
  { cat: { ar: 'مكان', en: 'Place' }, w: { ar: 'السوق', en: 'The market' } },
  { cat: { ar: 'مكان', en: 'Place' }, w: { ar: 'الشاطئ', en: 'The beach' } },
  { cat: { ar: 'مكان', en: 'Place' }, w: { ar: 'السينما', en: 'The cinema' } },
  { cat: { ar: 'مكان', en: 'Place' }, w: { ar: 'المسجد', en: 'The mosque' } },
  { cat: { ar: 'مكان', en: 'Place' }, w: { ar: 'الاستراحة', en: 'The chalet' } },
  { cat: { ar: 'مكان', en: 'Place' }, w: { ar: 'الفندق', en: 'The hotel' } },
  { cat: { ar: 'مكان', en: 'Place' }, w: { ar: 'الجامعة', en: 'The university' } },
  { cat: { ar: 'مهنة', en: 'Job' }, w: { ar: 'طبيب', en: 'Doctor' } },
  { cat: { ar: 'مهنة', en: 'Job' }, w: { ar: 'معلم', en: 'Teacher' } },
  { cat: { ar: 'مهنة', en: 'Job' }, w: { ar: 'طيار', en: 'Pilot' } },
  { cat: { ar: 'مهنة', en: 'Job' }, w: { ar: 'شرطي', en: 'Police officer' } },
  { cat: { ar: 'مهنة', en: 'Job' }, w: { ar: 'طباخ', en: 'Chef' } },
  { cat: { ar: 'مهنة', en: 'Job' }, w: { ar: 'مصور', en: 'Photographer' } },
  { cat: { ar: 'أكل', en: 'Food' }, w: { ar: 'كبسة', en: 'Kabsa' } },
  { cat: { ar: 'أكل', en: 'Food' }, w: { ar: 'بيتزا', en: 'Pizza' } },
  { cat: { ar: 'أكل', en: 'Food' }, w: { ar: 'تمر', en: 'Dates' } },
  { cat: { ar: 'أكل', en: 'Food' }, w: { ar: 'شاورما', en: 'Shawarma' } },
  { cat: { ar: 'أكل', en: 'Food' }, w: { ar: 'آيسكريم', en: 'Ice cream' } },
  { cat: { ar: 'أكل', en: 'Food' }, w: { ar: 'قهوة', en: 'Coffee' } },
  { cat: { ar: 'حيوان', en: 'Animal' }, w: { ar: 'الجمل', en: 'The camel' } },
  { cat: { ar: 'حيوان', en: 'Animal' }, w: { ar: 'القطة', en: 'The cat' } },
  { cat: { ar: 'حيوان', en: 'Animal' }, w: { ar: 'الأسد', en: 'The lion' } },
  { cat: { ar: 'حيوان', en: 'Animal' }, w: { ar: 'النسر', en: 'The eagle' } },
  { cat: { ar: 'حيوان', en: 'Animal' }, w: { ar: 'الحصان', en: 'The horse' } },
  { cat: { ar: 'غرض', en: 'Object' }, w: { ar: 'الجوال', en: 'The phone' } },
  { cat: { ar: 'غرض', en: 'Object' }, w: { ar: 'المفتاح', en: 'The key' } },
  { cat: { ar: 'غرض', en: 'Object' }, w: { ar: 'الساعة', en: 'The watch' } },
  { cat: { ar: 'غرض', en: 'Object' }, w: { ar: 'النظارة', en: 'The glasses' } },
  { cat: { ar: 'غرض', en: 'Object' }, w: { ar: 'الحقيبة', en: 'The bag' } },
  { cat: { ar: 'غرض', en: 'Object' }, w: { ar: 'المروحة', en: 'The fan' } },
  { cat: { ar: 'نشاط', en: 'Activity' }, w: { ar: 'الغوص', en: 'Diving' } },
  { cat: { ar: 'نشاط', en: 'Activity' }, w: { ar: 'التخييم', en: 'Camping' } },
  { cat: { ar: 'نشاط', en: 'Activity' }, w: { ar: 'التسوق', en: 'Shopping' } },
  { cat: { ar: 'نشاط', en: 'Activity' }, w: { ar: 'القراءة', en: 'Reading' } },
  { cat: { ar: 'رياضة', en: 'Sport' }, w: { ar: 'كرة القدم', en: 'Football' } },
  { cat: { ar: 'رياضة', en: 'Sport' }, w: { ar: 'السباحة', en: 'Swimming' } },
  { cat: { ar: 'رياضة', en: 'Sport' }, w: { ar: 'الجري', en: 'Running' } },
  { cat: { ar: 'مكان', en: 'Place' }, w: { ar: 'المكتبة', en: 'The library' } },
  { cat: { ar: 'مكان', en: 'Place' }, w: { ar: 'الصيدلية', en: 'The pharmacy' } },
  { cat: { ar: 'مكان', en: 'Place' }, w: { ar: 'محطة الوقود', en: 'The petrol station' } },
  { cat: { ar: 'مكان', en: 'Place' }, w: { ar: 'صالة الرياضة', en: 'The gym' } },
  { cat: { ar: 'مهنة', en: 'Job' }, w: { ar: 'مهندس', en: 'Engineer' } },
  { cat: { ar: 'مهنة', en: 'Job' }, w: { ar: 'محامي', en: 'Lawyer' } },
  { cat: { ar: 'مهنة', en: 'Job' }, w: { ar: 'نجار', en: 'Carpenter' } },
  { cat: { ar: 'مهنة', en: 'Job' }, w: { ar: 'صحفي', en: 'Journalist' } },
  { cat: { ar: 'أكل', en: 'Food' }, w: { ar: 'مندي', en: 'Mandi' } },
  { cat: { ar: 'أكل', en: 'Food' }, w: { ar: 'فلافل', en: 'Falafel' } },
  { cat: { ar: 'أكل', en: 'Food' }, w: { ar: 'معكرونة', en: 'Pasta' } },
  { cat: { ar: 'حيوان', en: 'Animal' }, w: { ar: 'الذئب', en: 'The wolf' } },
  { cat: { ar: 'حيوان', en: 'Animal' }, w: { ar: 'السلحفاة', en: 'The turtle' } },
  { cat: { ar: 'حيوان', en: 'Animal' }, w: { ar: 'الفراشة', en: 'The butterfly' } },
  { cat: { ar: 'غرض', en: 'Object' }, w: { ar: 'المظلة', en: 'The umbrella' } },
  { cat: { ar: 'غرض', en: 'Object' }, w: { ar: 'المرآة', en: 'The mirror' } },
  { cat: { ar: 'غرض', en: 'Object' }, w: { ar: 'السلم', en: 'The ladder' } },
  { cat: { ar: 'نشاط', en: 'Activity' }, w: { ar: 'الطبخ', en: 'Cooking' } },
  { cat: { ar: 'نشاط', en: 'Activity' }, w: { ar: 'الرسم', en: 'Drawing' } },
  { cat: { ar: 'رياضة', en: 'Sport' }, w: { ar: 'التنس', en: 'Tennis' } },
  { cat: { ar: 'رياضة', en: 'Sport' }, w: { ar: 'الملاكمة', en: 'Boxing' } },
];

module.exports = { bluff, number, blitz, likely, emoji, spy };
